// Generated by gencpp from file walker_msgs/BBox2D.msg
// DO NOT EDIT!


#ifndef WALKER_MSGS_MESSAGE_BBOX2D_H
#define WALKER_MSGS_MESSAGE_BBOX2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace walker_msgs
{
template <class ContainerAllocator>
struct BBox2D_
{
  typedef BBox2D_<ContainerAllocator> Type;

  BBox2D_()
    : id(0)
    , class_name()
    , score(0.0)
    , center()
    , size_x(0.0)
    , size_y(0.0)  {
    }
  BBox2D_(const ContainerAllocator& _alloc)
    : id(0)
    , class_name(_alloc)
    , score(0.0)
    , center(_alloc)
    , size_x(0.0)
    , size_y(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_name_type;
  _class_name_type class_name;

   typedef float _score_type;
  _score_type score;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef float _size_x_type;
  _size_x_type size_x;

   typedef float _size_y_type;
  _size_y_type size_y;





  typedef boost::shared_ptr< ::walker_msgs::BBox2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walker_msgs::BBox2D_<ContainerAllocator> const> ConstPtr;

}; // struct BBox2D_

typedef ::walker_msgs::BBox2D_<std::allocator<void> > BBox2D;

typedef boost::shared_ptr< ::walker_msgs::BBox2D > BBox2DPtr;
typedef boost::shared_ptr< ::walker_msgs::BBox2D const> BBox2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::walker_msgs::BBox2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::walker_msgs::BBox2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::walker_msgs::BBox2D_<ContainerAllocator1> & lhs, const ::walker_msgs::BBox2D_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.class_name == rhs.class_name &&
    lhs.score == rhs.score &&
    lhs.center == rhs.center &&
    lhs.size_x == rhs.size_x &&
    lhs.size_y == rhs.size_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::walker_msgs::BBox2D_<ContainerAllocator1> & lhs, const ::walker_msgs::BBox2D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace walker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::BBox2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::BBox2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::BBox2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::BBox2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::BBox2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::BBox2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::walker_msgs::BBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c77df3d2730bffc00b93fb5799a0241";
  }

  static const char* value(const ::walker_msgs::BBox2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c77df3d2730bffcULL;
  static const uint64_t static_value2 = 0x00b93fb5799a0241ULL;
};

template<class ContainerAllocator>
struct DataType< ::walker_msgs::BBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walker_msgs/BBox2D";
  }

  static const char* value(const ::walker_msgs::BBox2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::walker_msgs::BBox2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string class_name\n"
"float32 score\n"
"\n"
"geometry_msgs/Pose2D center\n"
"float32 size_x\n"
"float32 size_y\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::walker_msgs::BBox2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::walker_msgs::BBox2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.class_name);
      stream.next(m.score);
      stream.next(m.center);
      stream.next(m.size_x);
      stream.next(m.size_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBox2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walker_msgs::BBox2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::walker_msgs::BBox2D_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_name);
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "size_x: ";
    Printer<float>::stream(s, indent + "  ", v.size_x);
    s << indent << "size_y: ";
    Printer<float>::stream(s, indent + "  ", v.size_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALKER_MSGS_MESSAGE_BBOX2D_H
