// Generated by gencpp from file walker_msgs/Det3D.msg
// DO NOT EDIT!


#ifndef WALKER_MSGS_MESSAGE_DET3D_H
#define WALKER_MSGS_MESSAGE_DET3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace walker_msgs
{
template <class ContainerAllocator>
struct Det3D_
{
  typedef Det3D_<ContainerAllocator> Type;

  Det3D_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , radius(0.0)
    , confidence(0.0)
    , class_name()
    , class_id(0)
    , h(0.0)
    , w(0.0)
    , l(0.0)  {
    }
  Det3D_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , radius(0.0)
    , confidence(0.0)
    , class_name(_alloc)
    , class_id(0)
    , h(0.0)
    , w(0.0)
    , l(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _radius_type;
  _radius_type radius;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_name_type;
  _class_name_type class_name;

   typedef int8_t _class_id_type;
  _class_id_type class_id;

   typedef float _h_type;
  _h_type h;

   typedef float _w_type;
  _w_type w;

   typedef float _l_type;
  _l_type l;





  typedef boost::shared_ptr< ::walker_msgs::Det3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walker_msgs::Det3D_<ContainerAllocator> const> ConstPtr;

}; // struct Det3D_

typedef ::walker_msgs::Det3D_<std::allocator<void> > Det3D;

typedef boost::shared_ptr< ::walker_msgs::Det3D > Det3DPtr;
typedef boost::shared_ptr< ::walker_msgs::Det3D const> Det3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::walker_msgs::Det3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::walker_msgs::Det3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::walker_msgs::Det3D_<ContainerAllocator1> & lhs, const ::walker_msgs::Det3D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw &&
    lhs.radius == rhs.radius &&
    lhs.confidence == rhs.confidence &&
    lhs.class_name == rhs.class_name &&
    lhs.class_id == rhs.class_id &&
    lhs.h == rhs.h &&
    lhs.w == rhs.w &&
    lhs.l == rhs.l;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::walker_msgs::Det3D_<ContainerAllocator1> & lhs, const ::walker_msgs::Det3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace walker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Det3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Det3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Det3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Det3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Det3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Det3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::walker_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7da55de3f441fc2374979407d5fddda3";
  }

  static const char* value(const ::walker_msgs::Det3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7da55de3f441fc23ULL;
  static const uint64_t static_value2 = 0x74979407d5fddda3ULL;
};

template<class ContainerAllocator>
struct DataType< ::walker_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walker_msgs/Det3D";
  }

  static const char* value(const ::walker_msgs::Det3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::walker_msgs::Det3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 yaw\n"
"float32 radius\n"
"float32 confidence\n"
"string class_name\n"
"int8 class_id\n"
"\n"
"float32 h\n"
"float32 w\n"
"float32 l\n"
;
  }

  static const char* value(const ::walker_msgs::Det3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::walker_msgs::Det3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.radius);
      stream.next(m.confidence);
      stream.next(m.class_name);
      stream.next(m.class_id);
      stream.next(m.h);
      stream.next(m.w);
      stream.next(m.l);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Det3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walker_msgs::Det3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::walker_msgs::Det3D_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "radius: ";
    Printer<float>::stream(s, indent + "  ", v.radius);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_name);
    s << indent << "class_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "l: ";
    Printer<float>::stream(s, indent + "  ", v.l);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALKER_MSGS_MESSAGE_DET3D_H
