// Generated by gencpp from file walker_msgs/Detection2DTriggerResponse.msg
// DO NOT EDIT!


#ifndef WALKER_MSGS_MESSAGE_DETECTION2DTRIGGERRESPONSE_H
#define WALKER_MSGS_MESSAGE_DETECTION2DTRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <walker_msgs/Detection2D.h>

namespace walker_msgs
{
template <class ContainerAllocator>
struct Detection2DTriggerResponse_
{
  typedef Detection2DTriggerResponse_<ContainerAllocator> Type;

  Detection2DTriggerResponse_()
    : result()  {
    }
  Detection2DTriggerResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::walker_msgs::Detection2D_<ContainerAllocator>  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Detection2DTriggerResponse_

typedef ::walker_msgs::Detection2DTriggerResponse_<std::allocator<void> > Detection2DTriggerResponse;

typedef boost::shared_ptr< ::walker_msgs::Detection2DTriggerResponse > Detection2DTriggerResponsePtr;
typedef boost::shared_ptr< ::walker_msgs::Detection2DTriggerResponse const> Detection2DTriggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator1> & lhs, const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator1> & lhs, const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace walker_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21fa1171234f74a411cb3db23c6d5c03";
  }

  static const char* value(const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21fa1171234f74a4ULL;
  static const uint64_t static_value2 = 0x11cb3db23c6d5c03ULL;
};

template<class ContainerAllocator>
struct DataType< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walker_msgs/Detection2DTriggerResponse";
  }

  static const char* value(const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walker_msgs/Detection2D result\n"
"\n"
"\n"
"================================================================================\n"
"MSG: walker_msgs/Detection2D\n"
"std_msgs/Header header\n"
"\n"
"walker_msgs/BBox2D[] boxes\n"
"\n"
"sensor_msgs/Image result_image\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: walker_msgs/BBox2D\n"
"int32 id\n"
"string class_name\n"
"float32 score\n"
"\n"
"geometry_msgs/Pose2D center\n"
"float32 size_x\n"
"float32 size_y\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection2DTriggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::walker_msgs::Detection2DTriggerResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::walker_msgs::Detection2D_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALKER_MSGS_MESSAGE_DETECTION2DTRIGGERRESPONSE_H
